export const DISCOVERY_CATEGORIES = [
  "Ristoranti",
  "Pizzerie",
  "Bar ed enoteche",
  "Agriturismi",
  "Gelaterie",
  "Pasticcerie",
  "Hotel",
  "Bed & Breakfast",
  "Agenzie immobiliari",
  "Studi legali",
  "Commercialisti",
  "Dentisti",
  "Fisioterapisti",
  "Cliniche private",
  "Farmacie",
  "Parrucchieri",
  "Barbieri",
  "Centri estetici",
  "Spa",
  "Palestre",
  "Personal trainer",
  "Scuole di danza",
  "Officine auto",
  "Concessionarie",
  "Imprese edili",
  "Idraulici",
  "Elettricisti",
  "Fotografi",
  "Wedding planner",
  "Negozi di abbigliamento",
  "Arredamento",
  "Agenzie di viaggio",
  "Scuole di formazione",
  "Consulenti aziendali",
] as const;
